### ISSUE TITLE
Images which are not accessible by public will not print

### ISSUE THREAD

**Issue by globalcow** [saltcorn/page-to-pdf#3]
So far, it is not possible to print pages which contain images which are not accessible by the public. This is obvious, as the Chromium browser is not authenticated in Saltcorn. It would be great, if this would be possible.

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/page-to-pdf/commit/a2d5676f8da5785485cf2e7792e31b53b9f5582b / released as v0.2.0

**Comment by glutamate** [comment]
@globalcow I just saw this is not working on linux (some linuxes?). You will need to upgrade to Saltcorn 0.8.3, which will be released soon. Fix is https://github.com/saltcorn/saltcorn/commit/c4aa2c434dadf9598178ac435f1c81cb97cb818e

**Comment by globalcow** [comment]
Hi @glutamate, thank you for the information. However, I am using it already with Saltcorn 0.8.0 on a Linux machine. It works fine and protected images are shown in the PDF!
